# Generated by Django 3.0.3 on 2020-02-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceProviderApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChairVector',
            new_name='HairVector',
        ),
        migrations.RenameField(
            model_name='hairvector',
            old_name='ChairVectorID',
            new_name='HairVectorID',
        ),
    ]
