# Generated by Django 3.0.3 on 2020-02-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceProviderApp', '0002_auto_20200225_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitVector',
            fields=[
                ('SuitVectorID', models.AutoField(primary_key=True, serialize=False)),
                ('Vector', models.TextField()),
                ('ImageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FaceProviderApp.Image')),
            ],
        ),
    ]
